name: "git changed top level dirs"
description: "Detects all top level directories that contain changes when compared against a base branch."

inputs:
  base_branch:
    description: "The branch to compare changes against"
    required: false
    default: "main"
  ignored_dirs:
    description: "A comma-separated list of directories to ignore"
    required: false
    default: ""
outputs:
  changed_dirs:
    description: "A json array containing the top level directories that contain changes"
    value: ${{ steps.detect.outputs.changed-dirs }}

runs:
  using: composite
  steps:
    - name: "â¬ Checkout Git repository"
      uses: actions/checkout@v4

    - name: "ðŸ”Ž Detect top level directories containing changes"
      id: detect
      shell: bash
      run: |
        base_branch=${{ inputs.base_branch }}
        base_branch="${base_branch#origin/}"

        git fetch origin "$base_branch"

        changed_dirs=$(git diff --name-only origin/"$base_branch" HEAD | grep '/' | cut -d'/' -f1 | uniq)
      
        IFS=','
        for dir in ${{ inputs.ignored_dirs }}; do
          changed_dirs=$(echo "$changed_dirs" | grep -v "$dir")
        done
      
        result=""
        IFS=$'\n'
        for dir in $changed_dirs; do
          result="$result$dir, "
        done
        echo "changed-dirs: [${result%, }]"
        echo "changed-dirs=[${result%, }]" >> $GITHUB_OUTPUT
