name: "🧪 Test (cd-ghcr)"
on:
  pull_request:
    paths:
      - ".github/workflows/cd-ghcr.test.yaml"
      - ".github/workflows/cd-ghcr.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cd-ghcr:
    uses: ./.github/workflows/cd-ghcr.yaml
    with:
      file: ./example-projects/docker-image/Dockerfile
      context: ./example-projects/docker-image/
      tags: ghcr.io/${{ github.repository }}:main,ghcr.io/${{ github.repository }}:latest
      labels: org.opencontainers.image.title=github-actions,org.opencontainers.image.url=https://github.com/maandr/github-actions
      timeout_minutes: 10
    secrets:
      GHCR_PAT: ${{ secrets.CONTAINER_REGISTRY_PAT }}
