name: "🧪 Test (ci-docker-image)"
on:
  pull_request:
    paths:
      - ".github/workflows/ci-docker-image.test.yaml"
      - ".github/workflows/ci-docker-image.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-docker-image:
    uses: ./.github/workflows/ci-docker-image.yaml
    with:
      file: ./example-projects/docker-image/Dockerfile
      context: ./example-projects/docker-image/
      timeout_minutes: 10
