name: "🧪 Test (gh-dependabot-config)"
on:
  pull_request:
    paths:
      - ".github/workflows/gh-dependabot-config.test.yaml"
      - ".github/workflows/gh-dependabot-config.yaml"

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-gh-dependabot-config
  cancel-in-progress: true

jobs:
  gh-dependabot-config:
    uses: ./.github/workflows/gh-dependabot-config.yaml
    with:
      output_file: .github/dependabot.yaml
      schedule: weekly
