name: "Test (Reusable Workflows)"
on:
  pull_request:
    paths-ignore:
      - '.github/actions/**'
      - '.github/workflows/test-composite-actions.yaml'
      - '.github/dependabot.yaml'
      - '.gitignore'
      - 'README.md'

jobs:
  test-ci-node:
    uses: ./.github/workflows/ci-node.yaml
    with:
      nodeVersion: 18.x
      lintCommand: pnpm lint
      testCommand: pnpm test
      buildCommand: pnpm build
      working-directory: ./tests/node/

  test-ci-docker-image:
    uses: ./.github/workflows/ci-docker-image.yaml
    with:
      file: ./tests/docker-image/Dockerfile
      context: ./tests/docker-image/

  test-generate-image-tags:
    uses: ./.github/workflows/cd-image-tags.yaml
    with:
      image: ghcr.io/${{ github.repository }}

  test-build-and-push-to-ghcr:
    uses: ./.github/workflows/cd-ghcr.yaml
    with:
      file: ./tests/docker-image/Dockerfile
      context: ./tests/docker-image/
      tags: ghcr.io/${{ github.repository }}:main,ghcr.io/${{ github.repository }}:latest
      labels: org.opencontainers.image.title=github-actions,org.opencontainers.image.url=https://github.com/maandr/github-actions
    secrets:
      GHCR_PAT: ${{ secrets.CONTAINER_REGISTRY_PAT }}
